theme: jekyll-theme-minimal
title: MicroFPGA
description: "An affordable and open-source FPGA platform for the electronic control of microscope.<br>
<ul>
  <li><a href=\"index.html\">Home</a></li>
  <li><a href=\"principle.html\">Principle</a></li>
  <li><a href=\"installation.html\">Installation</a></li>
  <li><a href=\"resources.html\">Resources</a></li>
  <li><a href=\"tutorials.html\">Tutorials</a></li>
  <li><a href=\"contact.html\">Contact</a></li>
</ul>"
logo: /img/logo.png
